# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dearsite', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=21, max_length=50, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=121, max_length=50, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
